apiVersion: v1
kind: Pod
metadata:
  name: vault
  labels:
    app: vault
spec:
  containers:
    - name: vault
      image: vault:latest
      ports:
        - name: web
          containerPort: 8200
          protocol: TCP